[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.openssl", "php82Extensions.mbstring", "php82Extensions.curl", "php82Extensions.gd", "composer"]

[phases.build]
cmds = ["composer install --no-dev --optimize-autoloader --ignore-platform-reqs"]

[start]
cmd = "php -S 0.0.0.0:$PORT"
